[MNG-5783] cobertura-maven-plugin:instrument failing NoClassDefFoundError: org/slf4j/LoggerFactory
o Updated to only test for plugin dependencies also part of Maven
  core to not getting filtered out. The list of plugin artifacts may
  differ using different Maven versions.